### ISSUE TITLE
minor vagrant provisioning error

### ISSUE THREAD

**Issue by heinburger** [moradology/CloudColony#10]
TASK: [ansible-postgresql | Drop database] ***********************************\* 
failed: [default] => {"failed": true}
msg: the python psycopg2 module is required

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/Users/stove/site.retry

default                    : ok=33   changed=26   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by heinburger** [comment]
doing this in vagrant ssh:
sudo pip install psycopg2

and then re-provisioning fixed it for me, but I couldn't find how to add that package to ansible

**Comment by moradology** [comment]
Good catch - I must have done this manually and not updated the requirements file (which can be found here: https://github.com/moradology/CloudColony/blob/develop/deploy/requirements.pip).

This is your commit. Go ahead and add a line for "psycopg2==2.5.4" and make a PR on that change

**Comment by moradology** [comment]
PR #11 fixed this.
